### ISSUE TITLE
RuntimeError: No such file or directory when running the hycom2bna.py script

### ISSUE THREAD

**Issue by ubernaut** [NOAA-ORR-ERD/GnomeTools#1]
Getting the following error when I run the hycom2bna.py script. I've tried it with both the example infilename and tried supplying it with one myself. I have tried executing the file where it exists and pulling the script out into another directory.  

It almost looks like it's trying to run a .c file. maybe there's something that isn't built yet? 

Thanks again. 

reading: hycom_hindcast_currents_2006_surface_marianas_gnome.nc
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\workspace\UAA-Geo\trunk\deps\GnomeTools-master\libgoods\scripts\hycom2bna.py", line 38, in <module>
    nc = netCDF4.Dataset(infilename)
  File "netCDF4_netCDF4.pyx", line 1547, in netCDF4._netCDF4.Dataset.__init__ (netCDF4_netCDF4.c:9837)
RuntimeError: No such file or directory

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- this looks as simple to me as the file is not where you are tellilng it, or has a different name.

The error is "RuntimeError: No such file or directory". The error is coming from a *.c file, because the actual file open call is in the c code (the netCDF4 c code, not GNOME's).
So check carefuly that :+1: 

hycom_hindcast_currents_2006_surface_marianas_gnome.nc

exists, and is named exactly that.

I suspect the issue may be the current working dir -- as you've given the name without a path, you need to be running this script from the dir the file is in. Alternately give it the full path to the file.

HTH,
-Chris
